# Generated by Django 5.2.5 on 2025-08-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
